In [28]:
import numpy as np
import pandas as pd

In [29]:
data=pd.read_csv(r"C:\Users\91987\Downloads\MarketPositioningofMobile\Market Positioning of Mobile\Dataset\Mobile_data.csv")

In [30]:
print(data.shape)

(2000, 15)


In [31]:
data.head()

battery_power  clock_speed  fc  int_memory  m_dep  mobile_wt  n_cores  pc  \
0            842          2.2   1           7    0.6        188        2   2   
1           1021          0.5   0          53    0.7        136        3   6   
2            563          0.5   2          41    0.9        145        5   6   
3            615          2.5   0          10    0.8        131        6   9   
4           1821          1.2  13          44    0.6        141        2  14   

   px_height  px_width   ram  sc_h  sc_w  talk_time  price_range  
0         20       756  2549     9     7         19            1  
1        905      1988  2631    17     3          7            2  
2       1263      1716  2603    11     2          9            2  
3       1216      1786  2769    16     8         11            2  
4       1208      1212  1411     8     2         15            1

In [32]:
data.describe(include='all')

battery_power  clock_speed           fc   int_memory        m_dep  \
count    2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean     1238.518500     1.522250     4.309500    32.046500     0.501750   
std       439.418206     0.816004     4.341444    18.145715     0.288416   
min       501.000000     0.500000     0.000000     2.000000     0.100000   
25%       851.750000     0.700000     1.000000    16.000000     0.200000   
50%      1226.000000     1.500000     3.000000    32.000000     0.500000   
75%      1615.250000     2.200000     7.000000    48.000000     0.800000   
max      1998.000000     3.000000    19.000000    64.000000     1.000000   

         mobile_wt      n_cores           pc    px_height     px_width  \
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000   
mean    140.249000     4.520500     9.916500   645.108000  1251.515500   
std      35.399655     2.287837     6.064315   443.780811   432.199447   
min      80.000000     1.000000     0.000000     0.000000   500.000000   
25%     109.000000     3.000000     5.000000   282.750000   874.750000   
50%     141.000000     4.000000    10.000000   564.000000  1247.000000   
75%     170.000000     7.000000    15.000000   947.250000  1633.000000   
max     200.000000     8.000000    20.000000  1960.000000  1998.000000   

               ram         sc_h         sc_w    talk_time  price_range  
count  2000.000000  2000.000000  2000.000000  2000.000000  2000.000000  
mean   2124.213000    12.306500     5.767000    11.011000     1.500000  
std    1084.732044     4.213245     4.356398     5.463955     1.118314  
min     256.000000     5.000000     0.000000     2.000000     0.000000  
25%    1207.500000     9.000000     2.000000     6.000000     0.750000  
50%    2146.500000    12.000000     5.000000    11.000000     1.500000  
75%    3064.500000    16.000000     9.000000    16.000000     2.250000  
max    3998.000000    19.000000    18.000000    20.000000     3.000000

In [33]:
data.isnull().sum()

battery_power    0
clock_speed      0
fc               0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
price_range      0
dtype: int64

In [34]:
X=data.values[:,0:-1]
Y=data.values[:,-1]

In [35]:
X.shape

(2000, 14)

In [36]:
Y.shape

(2000,)

In [37]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)
#X=scaler.fit_transform(X)
#print(X)

In [38]:
print(X)

[[-0.90259726  0.83077942 -0.76249466 ... -0.78498329  0.2831028
   1.46249332]
 [-0.49513857 -1.2530642  -0.99289039 ...  1.11426556 -0.63531667
  -0.73426721]
 [-1.5376865  -1.2530642  -0.53209893 ... -0.31017108 -0.86492153
  -0.36814045]
 ...
 [ 1.53077336 -0.76274805 -0.76249466 ... -0.78498329 -1.0945264
  -1.10039396]
 [ 0.62252745 -0.76274805 -0.07130748 ...  1.35167167  0.9719174
   1.46249332]
 [-1.65833069  0.58562134  0.15908825 ...  1.58907778 -0.4057118
  -1.6495841 ]]


In [39]:
Y=Y.astype(int)

In [40]:
from sklearn.model_selection import train_test_split
# Split the data into test and train
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=10)

In [41]:
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

(1600, 14)
(1600,)
(400, 14)
(400,)


In [49]:
# Predicting using the KNeighbors _Classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=30,metric='manhattan')

# euclidean, manhattan,minkowski
# fit the model on the data and predict the values 
model_KNN.fit(X_train,Y_train)

Y_pred=model_KNN.predict(X_test)

In [50]:
Y_pred

array([3, 2, 1, 3, 0, 3, 2, 3, 1, 3, 2, 3, 0, 1, 0, 3, 1, 3, 3, 2, 3, 2,
       0, 1, 0, 0, 3, 3, 1, 1, 2, 1, 3, 2, 2, 2, 1, 0, 1, 0, 3, 2, 2, 1,
       1, 3, 1, 0, 0, 2, 1, 2, 2, 2, 2, 3, 2, 3, 0, 0, 1, 1, 0, 0, 2, 0,
       2, 0, 2, 2, 2, 2, 0, 1, 3, 2, 3, 3, 2, 1, 2, 0, 1, 0, 0, 3, 2, 3,
       3, 3, 2, 3, 3, 3, 3, 1, 0, 0, 0, 1, 2, 0, 1, 2, 1, 3, 2, 1, 1, 2,
       2, 0, 3, 1, 2, 1, 1, 1, 3, 0, 0, 1, 3, 1, 1, 3, 1, 3, 2, 0, 3, 2,
       3, 0, 3, 0, 0, 3, 3, 1, 2, 0, 3, 2, 0, 3, 2, 2, 2, 0, 1, 0, 0, 2,
       1, 1, 0, 0, 2, 0, 1, 3, 3, 2, 1, 2, 1, 1, 2, 0, 3, 3, 3, 2, 0, 2,
       2, 2, 2, 1, 1, 2, 2, 2, 3, 0, 1, 3, 0, 2, 0, 2, 1, 3, 2, 0, 0, 0,
       0, 3, 1, 3, 3, 3, 3, 2, 2, 1, 2, 0, 2, 1, 1, 3, 2, 0, 3, 1, 2, 1,
       3, 2, 0, 3, 0, 1, 2, 2, 1, 2, 1, 1, 0, 3, 0, 2, 0, 2, 0, 3, 0, 2,
       1, 1, 1, 2, 2, 3, 0, 2, 1, 1, 0, 3, 1, 2, 2, 1, 1, 3, 3, 1, 1, 2,
       3, 2, 3, 0, 2, 2, 3, 2, 0, 3, 0, 3, 1, 2, 2, 0, 3, 3, 0, 1, 1, 2,
       2, 0, 0, 1, 2, 0, 3, 3, 2, 1, 2, 0, 0, 2, 0,

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[83  9  0  0]
 [17 64 16  0]
 [ 0 21 78 10]
 [ 0  0 21 81]]
Classification report: 
              precision    recall  f1-score   support

           0       0.83      0.90      0.86        92
           1       0.68      0.66      0.67        97
           2       0.68      0.72      0.70       109
           3       0.89      0.79      0.84       102

    accuracy                           0.77       400
   macro avg       0.77      0.77      0.77       400
weighted avg       0.77      0.77      0.77       400

Accuracy of the model:  0.765


In [52]:
# checking various k values which is best suitable
from sklearn.metrics import accuracy_score
my_dict={}
for K in range(1,51):
    model_KNN = KNeighborsClassifier(n_neighbors=K,metric="manhattan")
    model_KNN.fit(X_train, Y_train) 
    Y_pred = model_KNN.predict(X_test)
    print ("Accuracy is ", accuracy_score(Y_test,Y_pred), "for K-Value:",K)
    my_dict[K]=accuracy_score(Y_test,Y_pred)

Accuracy is  0.53 for K-Value: 1
Accuracy is  0.4875 for K-Value: 2
Accuracy is  0.54 for K-Value: 3
Accuracy is  0.5775 for K-Value: 4
Accuracy is  0.615 for K-Value: 5
Accuracy is  0.625 for K-Value: 6
Accuracy is  0.64 for K-Value: 7
Accuracy is  0.68 for K-Value: 8
Accuracy is  0.6625 for K-Value: 9
Accuracy is  0.6825 for K-Value: 10
Accuracy is  0.695 for K-Value: 11
Accuracy is  0.7125 for K-Value: 12
Accuracy is  0.695 for K-Value: 13
Accuracy is  0.705 for K-Value: 14
Accuracy is  0.7075 for K-Value: 15
Accuracy is  0.71 for K-Value: 16
Accuracy is  0.715 for K-Value: 17
Accuracy is  0.72 for K-Value: 18
Accuracy is  0.7175 for K-Value: 19
Accuracy is  0.7325 for K-Value: 20
Accuracy is  0.7175 for K-Value: 21
Accuracy is  0.7175 for K-Value: 22
Accuracy is  0.7275 for K-Value: 23
Accuracy is  0.7325 for K-Value: 24
Accuracy is  0.7375 for K-Value: 25
Accuracy is  0.74 for K-Value: 26
Accuracy is  0.7475 for K-Value: 27
Accuracy is  0.74 for K-Value: 28
Accuracy is  0.7575 for

In [53]:
for k in my_dict:
    if my_dict[k]==max(my_dict.values()):
        print(k,":",my_dict[k])

30 : 0.765


In [54]:
from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression()
#fitting training data to the model
classifier.fit(X_train,Y_train)

Y_pred=classifier.predict(X_test)
print(Y_pred)

[3 3 2 3 1 3 3 3 1 3 2 3 0 1 0 3 2 3 2 2 3 2 0 1 0 0 2 3 1 1 2 0 3 2 2 2 1
 1 2 0 3 2 2 0 1 3 1 0 1 2 1 3 2 3 2 3 2 3 0 0 1 1 0 0 2 0 2 1 2 3 2 2 1 1
 3 1 3 3 2 1 2 0 0 0 0 3 2 3 3 3 2 3 3 3 3 1 0 1 0 1 3 0 1 1 1 3 2 1 2 2 2
 0 3 1 2 1 1 2 3 0 1 0 3 2 1 3 0 3 2 0 3 3 3 1 2 0 0 3 3 1 3 0 3 2 0 3 3 1
 2 0 1 0 0 1 1 1 0 0 2 1 1 2 3 2 2 2 0 1 1 1 3 3 3 2 0 2 3 2 2 2 1 2 2 2 3
 0 2 3 0 2 0 2 1 3 2 0 0 0 0 3 1 3 3 3 2 2 1 2 2 1 2 1 1 3 2 0 3 1 2 1 3 2
 0 3 0 1 2 2 1 0 1 1 0 3 0 1 0 2 0 3 1 2 0 1 1 2 2 3 0 3 2 1 0 3 2 1 2 1 0
 3 3 1 1 1 3 2 3 0 2 2 2 2 0 3 0 3 1 1 2 0 3 3 0 1 1 1 3 0 0 1 1 0 2 2 2 1
 2 0 0 3 1 3 2 2 1 0 1 1 2 1 0 1 1 2 2 0 0 0 3 3 0 1 0 2 0 0 2 1 2 3 1 1 1
 1 2 2 2 2 2 2 2 2 3 0 3 1 1 3 0 1 0 1 3 2 3 3 0 3 3 1 1 2 0 3 0 3 2 0 2 0
 0 3 0 1 2 2 0 3 0 0 3 2 0 0 0 3 1 3 3 1 0 1 0 3 3 3 1 0 2 1]


In [55]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(Y_test,Y_pred)
print(cfm)

print("Classification report: ")

print(classification_report(Y_test,Y_pred))

acc=accuracy_score(Y_test, Y_pred)
print("Accuracy of the model: ",acc)

[[ 92   0   0   0]
 [  2  94   1   0]
 [  0   5 102   2]
 [  0   0   3  99]]
Classification report: 
              precision    recall  f1-score   support

           0       0.98      1.00      0.99        92
           1       0.95      0.97      0.96        97
           2       0.96      0.94      0.95       109
           3       0.98      0.97      0.98       102

    accuracy                           0.97       400
   macro avg       0.97      0.97      0.97       400
weighted avg       0.97      0.97      0.97       400

Accuracy of the model:  0.9675
